// eslint-disable-next-line
import './assets/favicon/*';
// eslint-disable-next-line
import './assets/fonts/*';
// eslint-disable-next-line
import './**/img/*';
// eslint-disable-next-line
import './**/init.js';
import './index.sass';
